### ISSUE TITLE
I created a fork

### ISSUE THREAD

**Issue by guizmaii** [yob/puma-plugin-statsd#3]
Hey @yob,

A little message just to let you know that I created a fork from your plugin here: https://github.com/guizmaii/puma-plugin-dogstatsd

I want to thank you for your work. You helped me a lot :)

Initially, I wanted to push you a PR because I wanted to simplify your code and change how the `statsd` client is booted: no environment variables, just pass an instance of a statsd client to the plugin (which is what I'm doing in my fork).

But, because I removed a lot of things from your plugin, I finally prefered to fork.

Let me know if your interested to merge some of my work in your plugin.
To me, the ideal situation could be that we merge our works. So you keep your plugin, and I delete mine.

Jules 🙂

**Comment by yob** [comment]
Thanks for sharing, your approach is a good one :sparkles: 

I think I'm happy to leave the broad structure of this gem as it is, but I'd be happy to cross-pollinate ideas and accept PRs for specific improvements if anyone is keen!
