### ISSUE TITLE
Parent process dying when statsd plugin fails to lookup DNS

### ISSUE THREAD

**Issue by tjsousa** [yob/puma-plugin-statsd#34]
Hi there,

We've observed a weird behaviour in Production at a relatively frequent rate where Puma will stop responding to the readiness probe in a Kubernetes cluster from time to time.

When correlating these occurrences with logs we've been able to isolate it to a DNS lookup failure when sending the statsd metrics through UDP and the workers dying precisely 2 seconds after the error is logged (which is consistent with the plugin handling of the error). However, we can't tell how this is leading to the master process dying:

```
2021-06-14 11:06:23.873 +0000 [8] ERROR: ! statsd: notify stats failed:   getaddrinfo: Temporary failure in name resolution
/usr/local/bundle/gems/puma-plugin-statsd-1.2.1/lib/puma/plugin/statsd.rb:23:in `send'
/usr/local/bundle/gems/puma-plugin-statsd-1.2.1/lib/puma/plugin/statsd.rb:23:in `send'
/usr/local/bundle/gems/puma-plugin-statsd-1.2.1/lib/puma/plugin/statsd.rb:177:in `block in stats_loop'
/usr/local/bundle/gems/puma-plugin-statsd-1.2.1/lib/puma/plugin/statsd.rb:171:in `loop'
/usr/local/bundle/gems/puma-plugin-statsd-1.2.1/lib/puma/plugin/statsd.rb:171:in `stats_loop'
/usr/local/bundle/gems/puma-5.3.1/lib/puma/plugin.rb:68:in `block (2 levels) in fire_background'
2021-06-14 11:06:25.873 +0000 [19] ! Detected parent died, dying
2021-06-14 11:06:25.873 +0000 [16] ! Detected parent died, dying
2021-06-14 11:06:25.873 +0000 [11] ! Detected parent died, dying
2021-06-14 11:06:25.873 +0000 [13] ! Detected parent died, dying
```

**Comment by tjsousa** [comment]
Looks like this is the intended behaviour of Puma when `@launcher.events.error` is used:
https://github.com/puma/puma/blame/master/lib/puma/events.rb#L83

The question here is if any error from the plugin should terminate the server?

**Comment by yob** [comment]
Wow, nice find. Apologies for crashing your servers!

> The question here is if any error from the plugin should terminate the server?

I'm quite confident I **don't** want an error in the plugin to terminate the server. Particularly a DNS error that is quite probably temporary or transient.

I'd happily accept a patch if you're keen? A rescue in `StatsdConnector#send` would presumably do the trick?

**Comment by tjsousa** [comment]
Another option is to use `@launcher.events.unknown_error` and never crash the server, what do you think?

https://github.com/puma/puma/blob/master/lib/puma/events.rb#L122-L124

I'm happy to open a patch in either direction you feel is the best for the project.

**Comment by tjsousa** [comment]
Have a working version of the proposed alternative here: https://github.com/yob/puma-plugin-statsd/pull/35

**Comment by yob** [comment]
#35 has merged, thanks!
