### ISSUE TITLE
Configure StatsD prefix

### ISSUE THREAD

**Issue by scalp42** [yob/puma-plugin-statsd#6]
Hi @yob,

Thanks a lot for the plugin.

Would it be possible to add an option to select the StatsD prefix?

Currently all the metrics start with `puma` but we'd like to be able to pass a prefix to namespace it (by environment for example).

Please let me know.

I should be able to create a PR as well, I'm just unsure on how to pass arguments, thinking something like this:

```ruby
plugin :statsd(prefix = 'production.')
```

Help would be much appreciated 🙇

**Comment by yob** [comment]
That sounds like a useful feature @scalp42.

I'm pretty flat out atm, but if you can prepare a PR I'm happy to review it.

**Comment by scalp42** [comment]
@yob unfortunately I'm unsure how to to pass arguments exactly. Once I figure that one out, I should be able to change the code easily.

**Comment by yob** [comment]
The existing convention in this gem is provide arguments via environment variables. I'd be happy to accept a PR that follows that convention for a prefix.
